### ISSUE TITLE
Warning message from pcor

### ISSUE THREAD

**Issue by feichel** [NetCoupler/NetCoupler#125]
When running `nc_plot_network`, the following error sometimes occurs:

Warning message:
In ppcor::pcor(.tbl) :
The inverse of variance-covariance matrix is calculated using Moore-Penrose generalized matrix invers due to its determinant of zero.

Code still works. So not sure how relevant this is.

**Comment by feichel** [comment]
The following error occurs in combination with the above error. This time, no plot is created:

Error in graph.adjacency.sparse(adjmatrix, mode = mode, weighted = weighted,  : 
  Please supply a symmetric matrix if you want to create a weighted graph with mode=UNDIRECTED.
In addition: Warning message:
In ppcor::pcor(.tbl) :
  The inverse of variance-covariance matrix is calculated using Moore-Penrose generalized matrix invers due to its determinant of zero.

**Comment by lwjohnst86** [comment]
Have you standardized the metabolites before putting into the network function? That would be my guess why you get that error, but its a ppcor error, not a NetCoupler error, so I don't know what the problem is.

**Comment by feichel** [comment]
All metabolites are log-transformed z-scores. Maybe this is normal behaviour of this package with so many variables?

**Comment by lwjohnst86** [comment]
Hmm, yea, I have no idea. How many variables?

**Comment by feichel** [comment]
I tried it a bit. It seems to depend on correlation structure as well. I used a set of three different lipid classes. It worked if I included 45 randomly selected species. It gave the a warning (first post), when I used 45 from the top (so only one class). The second error (and not displaying a network) happens around 100. But depends on correlation within the lipid class. TAG (high correlations) starts earlier

**Comment by feichel** [comment]
Btw, this error message pops up, sometimes in between. Probably has to do with the plotting not working or something. Can't robustly reproduce this. 

> warning message:
In valid.data(rep(units, length.out = length(x)), data) :
  reached elapsed time limit

**Comment by feichel** [comment]
Ok, after digging deeper into your code and trying a ton of things here is the solution. I would like to say there was a real theoretical consideration for trying this, but honestly, I just blindly tried out stuff =). 
It seems that igraph::graph.adjacency does not like it, when the weights have to many digits. Rounding did the trick. The code below should work.

```
 nc_adjacency_graph <- function(.tbl, .graph) {
    weighted_adjacency_matrix <- nc_adjacency_matrix(.graph) *
        round(nc_partial_corr_matrix(.tbl), digits = 3)

    igraph::graph.adjacency(weighted_adjacency_matrix,
                            weighted = TRUE, mode = "undirected")
} 
```

**Comment by lwjohnst86** [comment]
Amazing work! Really strange though. I'll add the code into the package... unless you wanna try doing it? :wink: You'd have to submit a Pull Request with the change.

**Comment by feichel** [comment]
Nah, please go ahead. =)

**Comment by lwjohnst86** [comment]
Sorry it took a while to address this. I've fixed it.
