### ISSUE TITLE
Comments from review of the website

### ISSUE THREAD

**Issue by danielibsen** [NetCoupler/NetCoupler#175]
## Here we can put our comments and suggestions for improvements on the website and assign who can work on what.

**Comment by danielibsen** [comment]
### ReadMe-file

- add overview figure/image of how the NetCoupler Algorithm - already on the to-do. 
- add links papers where the method has been used (to give examples)
- (eventually) add links to methods paper, where strengths and limitations of of the method could also be discussed
- Under the image it would be good to add the key assumption that: exposure has an effect on the -omics and that -omics has an effect on the outcome of interest. 
- based on the comment from Clemens in our meeting (https://github.com/NetCoupler/NetCoupler/issues/16#issuecomment-998011591), we should add that the intended use of this method: use for -omics as the network. We would not recommend using the methods for variables that are very different forming the network.

**Comment by danielibsen** [comment]
## Getting started

- add title 'references' in the bottom of the docs. 
- It was unclear when you should adjust for confounding when using the nc_stanardize function. As I understand it, it would only be when we are only interested in the network itself.
- add the criteria for selection of direct, ambiguous or none on links between exposure/outcome and -omics network 
- are there anything re the class of the variables used for adjustment and what about missing data, that will give an error?

**Comment by feichel** [comment]
**Getting started cont.**
-
- link to more in depth explanations in the "articles" pages. Depending on style some of the following points might be addressed in "getting started" or "articles"
- Could there be exceptions that don't need log-transform or a different transform? Possible/Useful to add something like rank transform?
- limitations: different LODs for different subclasses of the omics datasets could have undesired effects on network estimation? 
- other network estimation methods planned? (seems suggested by "default")


**Articles**
-
- More info on the PC-algorithm here and a more digestible (and short) explanation in readme/getting started?
- Link examples to underlying study designs? (e.g. case-cohort)
- Add logged runtime for the examples?

**General comments, not sure where to add**
-
- can be used without knowledge of tidyverse? Worth showing examples in more base style?
- Do we expect perfomance issues? Can some things be parallelized. Use of tidytable or dtplyr when dataframes get really large? Can add to issues. 
- necessary to model confounders in the exact same way in network estimation step and exposure/outcome?

**Comment by danielibsen** [comment]
## General comments

[ ]  the heading 'reference' at the top could be changed to 'Functions' - unless there will be more than functions added here

## Implementation details of NetCoupler

[ ] references do not work
[ ] agree with Fabian, more details on the PC-algorithm and note if there could be others to use as well
[ ] under 2., markov parents and d-separation may not be clear to everyone. We could add references of explain more. Will also depend on who the target audience is. 
[ ] under 3. time-to-event could be changed to 'outcome' to make it more generic. 
[ ] we could make this explantion of the algorithm more visual and put that in the README - then this could be the more detailed explanation.
[ ] we could add general notation/abbreviations in the beginning of the doc
[ ] numbering the paragraphs in the explanation would help the reader + adding a little overall explanation of the document in the beginning

## Examples of using NetCoupler with different models

[ ] add a header 'pre-processing' in the beginning
[ ] having multiple examples with different types of outcomes is really great and I think we should just add more text to the examples explaining what the aim of the analysis is, the variables we use etc.

**Comment by lwjohnst86** [comment]
Regarding some of @feichel comments:

- "Add logged runtime for the examples?" Because they are built into the package, the runtime for the examples are intentionally very very fast to limit problems with building the package.
- "can be used without knowledge of tidyverse? Worth showing examples in more base style?" We had a discussion about this in the discord channel. The only "truly" tidyverse thing is the `starts_with()` and other tidyselect functions. Since base R now has its own pipe `|>` that behaves almost identical (but not exactly) the same as the magrittr pipe, piping is no longer a tidyverse specific thing.
- "Do we expect perfomance issues? Can some things be parallelized. Use of tidytable or dtplyr when dataframes get really large? Can add to issues." Performance is definitely an issue we need to test out on larger datasets. I'd like to implement parallelization but that's for later. I tried to originally but it failed :stuck_out_tongue_closed_eyes:
