### ISSUE TITLE
List of functions

### ISSUE THREAD

**Issue by ClemensWittenbecher** [NetCoupler/NetCoupler#18]
# Functions the enduser will apply
## Standard_Mets
*Purpose*: Regress exposure (and possibly covariables) on metabolites to avoid confounded links between metabolites
*Input*: nxp matrix of n observations on p metabolites (numeric variables); nxq matrix of n observations on q adjustment variables (exposure and covariables) (numeric variables OR categorical OR binary variables)
*Output*: Adjusted metabolite_residuals as Input (ONLY!) for metabolomics network estimation, same format as input metabolite data_matrix
COMMENT This needs to be implemented in R. So far, preparation of the dataset was done in SAS.

## Get.Net
*Purpose*: Estimate the skeleton of the underlying DAG (i.e., the family of data-generating models that could have induced the observed conditional independence structure)
*Input*: adjmet_dat	nxp matrix of n observations on p adjusted metabolite_residuals (numeric variables)
*Output*: graph_skel	a graphNEL object encoding the skeleton of the DAG underlying the metabolomics data
COMMENT This needs to be summarized into one handy function.

## NC.in
*Purpose*: Identify direct exposure effects on metabolites (not mediated by other metabolites)
*Input*: graph_skel	a graphNEL object encoding the skeleton of the DAG underlying the metabolomics data met_dat	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function)
dat_compl	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function), typically same as dat ???ask Helena why this was included???
exp_dat	exposure/phenotype data that has a potential effect on metabolite concentrations in dat; contains exposure(s) of interest and optionally covariables that are possible confounders and should thus be included in the fixed adjustment set
DE	indicator if direct effects were already identified 
*Output*: model_details_all GLMulti object that contains for all metabolites details and results on the exposure effect from the set of models that were calculated by adjusting for every possible subset of direct network neighbors 
COMMENT Now a lot of information is stored and thus the object can be very big and can therefore block the work space. Should we integrate GET.functions  and only output small summary tables as a result as a default?

## NC.out
Purpose: Identify direct effects of metabolites on Typ 2 Diabetes risk (not confounded or mediated by other metabolites)
*Input*: graph_skel	a graphNEL object encoding the skeleton of the DAG underlying the metabolomics data met_dat	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function)
dat_compl	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function), typically same as dat ???ask Helena why this was included???
exp_dat	optional exposure/phenotype data containing a set of covariables that are possible confounders and should thus be included in the fixed adjustment set
always_set	names of variables in exp_dat that should always be included in the model in terms of adjustment for confounders
survival_obj	survival object containing case status and survival time information
DE	indicator if direct effects were already identified 
*Output*: model_details_all	GLMulti object that contains for all metabolites details and results on their possible effects on type 2 diabetes risk from the set of models that were calculated by adjusting for every possible subset of direct network neighbors 
COMMENT Now a lot of information is stored and thus the object can be very big and can therefore block the work space. Should we integrate GET.functions  and only output small summary tables as a result as a default?

**Comment by ClemensWittenbecher** [comment]
# Functions the enduser will apply
_Task_: structured list with headers
* main functions - default workflow for the enduser to generate a coupled network: [exposure]->[metabolites]->[outcome])

and subheaders
* support functions - helpers to prepare the input data and getters to summarize the output

also include status and tasks to
 
## Standard_Mets
*Purpose*: Regress exposure (and possibly covariables) on metabolites to avoid confounded links between metabolites
*Input*: nxp matrix of n observations on p metabolites (numeric variables); nxq matrix of n observations on q adjustment variables (exposure and covariables) (numeric variables OR categorical OR binary variables)
*Output*: Adjusted metabolite_residuals as Input (ONLY!) for metabolomics network estimation, same format as input metabolite data_matrix
COMMENT This needs to be implemented in R. So far, preparation of the dataset was done in SAS.

## Get.Net
*Purpose*: Estimate the skeleton of the underlying DAG (i.e., the family of data-generating models that could have induced the observed conditional independence structure)
*Input*: adjmet_dat	nxp matrix of n observations on p adjusted metabolite_residuals (numeric variables)
*Output*: graph_skel	a graphNEL object encoding the skeleton of the DAG underlying the metabolomics data


## NC.in
*Purpose*: Identify direct exposure effects on metabolites (not mediated by other metabolites)
*Input*: graph_skel	a graphNEL object encoding the skeleton of the DAG underlying the metabolomics data met_dat	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function)
dat_compl	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function), typically same as dat ???ask Helena why this was included???
exp_dat	exposure/phenotype data that has a potential effect on metabolite concentrations in dat; contains exposure(s) of interest and optionally covariables that are possible confounders and should thus be included in the fixed adjustment set
DE	indicator if direct effects were already identified 
*Output*: model_details_all GLMulti object that contains for all metabolites details and results on the exposure effect from the set of models that were calculated by adjusting for every possible subset of direct network neighbors 
COMMENT Now a lot of information is stored and thus the object can be very big and can therefore block the work space. Should we integrate GET.functions  and only output small summary tables as a result as a default?

## NC.out
Purpose: Identify direct effects of metabolites on Typ 2 Diabetes risk (not confounded or mediated by other metabolites)
*Input*: graph_skel	a graphNEL object encoding the skeleton of the DAG underlying the metabolomics data met_dat	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function)
dat_compl	nxp matrix of n observations on p metabolites (numeric variables); variable names need to be short! strings (use rename function), typically same as dat ???ask Helena why this was included???
exp_dat	optional exposure/phenotype data containing a set of covariables that are possible confounders and should thus be included in the fixed adjustment set
always_set	names of variables in exp_dat that should always be included in the model in terms of adjustment for confounders
survival_obj	survival object containing case status and survival time information
DE	indicator if direct effects were already identified 
*Output*: model_details_all	GLMulti object that contains for all metabolites details and results on their possible effects on type 2 diabetes risk from the set of models that were calculated by adjusting for every possible subset of direct network neighbors 
COMMENT Now a lot of information is stored and thus the object can be very big and can therefore block the work space. Should we integrate GET.functions  and only output small summary tables as a result as a default?

## Get.Exp.Coef.in
## Classify.in
## Get.Exp.Coef.in
## Classify.out
## Make.Coupled.NW

**Comment by lwjohnst86** [comment]
As per our discussion in Berlin (Oct. 5th).

- `nc_compute(data, graph_file)`: Start the NetCoupler. Data is the metabolomics data. `graph_file` is the optional argument that indicates the links between each variables. I don't love the name... we'll think on this more.
- `nc_create_network(data)`: To create the network for use in NetCoupler. Could be the default if no `graph_file` argument is given. The output could be a tibble with nested lists, for each start node and end node. **This function is a priority**.
- `nc_outcome_estimates(data, outcome, graph_file)`: Calculate the estimates between the outcome and metabolomics. **This is a priority**.
- `nc_exposure_estimates(data, exposure, graph_file)`: Calculate the estimates between exposure and metabolomics data.
- `nc_estimates(data, variable, graph_file)`: A generalisation of the outcome and exposure functions above. `variable` can be either the outcome or the exposure.

**Comment by lwjohnst86** [comment]
These have pretty much been implemented so far. Closing this.
