### ISSUE TITLE
nc_create_network(data) : Optimize and test function

### ISSUE THREAD

**Issue by ClemensWittenbecher** [NetCoupler/NetCoupler#22]
# Optimize
- [x] select and implement network-estimation algorithms
- [x] review check functions for input format
- [x] define output format
    - Output as a graph
- [ ] auxilliary functions to standardize metabolomics data
# Test
- [x] create test dataset(s) according to user-defined DAG
- [x] test functionality with toy data
- [ ] define performance measures for causal structure learning
This is a subtask of issue #18

**Comment by lwjohnst86** [comment]
Done in #52

**Comment by ClemensWittenbecher** [comment]
Hi Luke,

Sorry for all delays and missing communication. I am really embarrassed that I didn't get back to you. The reason is that I was asked to write a paper in very limited time on a timely issue (not sure if you were aware of the red meat discussion). Exciting but also quite stressful. I just get a little air again, and I will use every resource to work on the NetCoupler-project. Thanks a lot for your contributions. I will now be more responsive again.

Clemens  


>>> Luke W Johnston <notifications@github.com> 19.11.19 12.10 Uhr >>>
Closed #22.

-- 
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub:
https://github.com/NetCoupler/NetCoupler/issues/22#event-2812262888

**Comment by lwjohnst86** [comment]
Hey Clemens, don't worry about it at alllll! I've also been super busy, and just now needing to focus on developing NetCoupler for my own use.

And yes, I did read about that red meat discussion. Did you finish it up?? What was it about? That does sound exciting! 

And no worries, right now I'm just going through and generalizing the code and adding unit tests. So you don't need to get involved just yet :) When we start getting into removing some of the dependencies (like glmulti), lets set up a meeting to talk about next steps and what to do then.
